#"C:/Program Files/7-Zip/7z.exe"
name: "Install SoX and add to PATH"
description: "Install SoX and add to PATH"
runs:
  using: "composite"
  steps:
    - run: |
       
        
        echo `pwd`


      shell: bash

