
name: "Install SoX and add to PATH"
description: "Install SoX and add to PATH"
runs:
  using: "composite"
  steps:
    - run: |
        set -ex
        curl -L --output sox-14.4.2-win32.zip --url https://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2-win32.zip/download
        "C:/Program Files/7-Zip/7z.exe" x -o`pwd`/bin/ -tzip -aoa sox-14.4.2-win32.zip
        rm sox-*zip
        echo "`pwd`/bin/sox-14.4.2/" >> $GITHUB_PATH
        cp D:\a\aicure_opendbm\aicure_opendbm\bin\sox-14.4.2\sox.exe C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
        cp D:\a\aicure_opendbm\aicure_opendbm\bin\sox-14.4.2\sox.exe C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts

      shell: bash