name: 📚 OpenDBM Documentation Issue
description: Report a documentation issue related to https://aicure.com/opendbm/docs/stable/index.html

body:
- type: textarea
  attributes:
    label: 📚 The doc issue
    description: >
      A clear and concise description of what content in https://aicure.com/opendbm/docs/stable/index.html is an issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!