# This workflow will check OpenDMB linting and format the code if necessary, and also sorted the import text
# For more information see: https://www.aicure.com/open_dbm#cicd

name: Test Code Checking

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install_code_checking_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Test code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install code checking dependencies
      run: |
        pip install flake8 pytest safety

  vulnerability_scanning:
    runs-on: ubuntu-latest
    needs: install_code_checking_dependencies
    steps:
    - name: Checkout Test code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Run safety
      shell: bash -l {0}
      run: |
        safety check
