# This workflow will check OpenDMB linting and format the code if necessary, and also sorted the import text
# For more information see: https://www.aicure.com/open_dbm#cicd

name: OpenDBM Code Checking

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenDBM code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run flake8
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics

  vulnerability_scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenDBM code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run safety
      run: |
        pip install safety
        safety check
